# zooplus Assistant — interactive local setup wizard (Windows)
# Usage: .\scripts\setup_wizard.ps1
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $Root

function Write-Step($n, $msg) { Write-Host ""; Write-Host "==> Step $n : $msg" -ForegroundColor Cyan }
function Write-Ok($msg) { Write-Host "    OK: $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "    WARN: $msg" -ForegroundColor Yellow }

Write-Host ""
Write-Host "========================================" -ForegroundColor White
Write-Host "  zooplus Assistant — Setup Wizard" -ForegroundColor White
Write-Host "  Branch: $(git branch --show-current 2>$null)" -ForegroundColor DarkGray
Write-Host "========================================" -ForegroundColor White

# --- Step 1: Python 3.11 ---
Write-Step 1 "Check Python 3.11"
$Py = $null
foreach ($cmd in @("py -3.11", "python3.11", "python")) {
    try {
        $exe = if ($cmd -eq "py -3.11") {
            & py -3.11 -c "import sys; print(sys.executable)" 2>$null
        } else {
            & $cmd -c "import sys; print(sys.executable)" 2>$null
        }
        if ($exe -and (Test-Path $exe.Trim())) {
            $ver = & $exe.Trim() -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')"
            if ($ver -eq "3.11") { $Py = $exe.Trim(); break }
        }
    } catch { }
}
if (-not $Py) {
    Write-Host "    ERROR: Python 3.11 not found." -ForegroundColor Red
    Write-Host "    Install: https://www.python.org/downloads/  or  py install 3.11"
    exit 1
}
Write-Ok "Using $Py ($(& $Py -c 'import sys; print(sys.version.split()[0])'))"

# --- Step 2: Virtual environment ---
Write-Step 2 "Virtual environment"
$Venv = Join-Path $Root ".venv"
$VenvPy = Join-Path $Venv "Scripts\python.exe"
if (-not (Test-Path $VenvPy)) {
    Write-Host "    Creating .venv ..."
    & $Py -m venv $Venv
}
$Py = $VenvPy
Write-Ok ".venv ready — activate: .\.venv\Scripts\Activate.ps1"

# --- Step 3: Dependencies ---
Write-Step 3 "Install dependencies (rag + dev)"
& $Py -m pip install -q --upgrade pip
& $Py -m pip install -q -e ".[rag,dev]"
Write-Ok "pip install -e .[rag,dev]"

# --- Step 4: Mode selection ---
Write-Step 4 "Choose runtime mode"
Write-Host ""
Write-Host "  [1] TEMPLATE — no OpenCode, no login (fastest, tests-friendly)"
Write-Host "  [2] OPENCODE  — agentic demo with free LLMs (requires opencode auth login)"
Write-Host ""
$choice = Read-Host "    Enter 1 or 2 (default 1)"
if (-not $choice) { $choice = "1" }

$EnvPath = Join-Path $Root ".env"
if ($choice -eq "2") {
    @"
# Generated by setup_wizard.ps1 — OpenCode agentic profile
ZOOPLUS_RETRIEVAL_MODE=hybrid
ZOOPLUS_INTENT_MODE=agentic
ZOOPLUS_SYNTHESIS_MODE=opencode
ZOOPLUS_SOCIAL_SYNTHESIS=agentic
ZOOPLUS_AGENT_CASCADE=1
ZOOPLUS_OPENCODE_MODEL=opencode/deepseek-v4-flash-free
ZOOPLUS_OPENCODE_TIMEOUT=45
ZOOPLUS_OPENCODE_DATA_DIR=.opencode/data
ZOOPLUS_OPENCODE_CONFIG_DIR=.opencode/config-cli
ZOOPLUS_DEV_PORT=8090
"@ | Set-Content -Path $EnvPath -Encoding UTF8
    Write-Ok "Wrote .env (OpenCode agentic profile)"
} else {
    @"
# Generated by setup_wizard.ps1 — template profile (no OpenCode)
ZOOPLUS_RETRIEVAL_MODE=hybrid
ZOOPLUS_INTENT_MODE=oracle
ZOOPLUS_SYNTHESIS_MODE=template
ZOOPLUS_SOCIAL_SYNTHESIS=agentic
ZOOPLUS_AGENT_CASCADE=0
ZOOPLUS_DEV_PORT=8090
"@ | Set-Content -Path $EnvPath -Encoding UTF8
    Write-Ok "Wrote .env (template profile)"
}

# Load .env into process
Get-Content $EnvPath -Encoding UTF8 | ForEach-Object {
    $line = $_.Trim()
    if ($line -and -not $line.StartsWith("#") -and $line -match "^([^=]+)=(.*)$") {
        Set-Item -Path "Env:$($matches[1].Trim())" -Value $matches[2].Trim().Trim('"').Trim("'")
    }
}

# --- Step 5: OpenCode (mode 2 only) ---
if ($choice -eq "2") {
    Write-Step 5 "OpenCode login"
    $DataDir = Join-Path $Root ".opencode\data"
    $ConfigDir = Join-Path $Root ".opencode\config-cli"
    New-Item -ItemType Directory -Force -Path $DataDir | Out-Null
    $env:OPENCODE_DATA_DIR = $DataDir
    $env:OPENCODE_CONFIG_DIR = $ConfigDir
    $GlobalAuth = Join-Path $env:USERPROFILE ".local\share\opencode\auth.json"
    $LocalAuth = Join-Path $DataDir "auth.json"

    $oc = Get-Command opencode -ErrorAction SilentlyContinue
    if (-not $oc) {
        Write-Warn "OpenCode CLI not in PATH."
        Write-Host "    Install: https://opencode.ai/docs/cli/"
        Write-Host "    Then re-run: .\scripts\setup_opencode_local.ps1"
    } elseif (Test-Path $GlobalAuth) {
        Copy-Item $GlobalAuth $LocalAuth -Force
        Write-Ok "Copied global auth to .opencode/data/auth.json (gitignored)"
    } elseif (Test-Path $LocalAuth) {
        Write-Ok "Existing project auth found"
    } else {
        Write-Host "    Browser login will open. Credentials go to .opencode/data/ (never committed)."
        $go = Read-Host "    Run 'opencode auth login' now? [Y/n]"
        if ($go -ne "n" -and $go -ne "N") {
            & opencode auth login
            if (Test-Path $LocalAuth) { Write-Ok "OpenCode login saved" }
            else { Write-Warn "No auth.json yet — app will use template fallback" }
        }
    }
} else {
    Write-Step 5 "OpenCode (skipped — template mode)"
    Write-Ok "No OpenCode required for this profile"
}

# --- Step 6: Ingest ---
Write-Step 6 "Build catalog index (Chroma)"
$manifest = Join-Path $Root "artifacts\index\manifest.json"
if (-not (Test-Path $manifest)) {
    & $Py -m cli ingest
    Write-Ok "Ingest complete"
} else {
    Write-Ok "Index already present ($manifest)"
}

# --- Step 7: Smoke test ---
Write-Step 7 "Quick smoke test (optional)"
$runSmoke = Read-Host "    Run smoke_minimal.ps1? [Y/n]"
if ($runSmoke -ne "n" -and $runSmoke -ne "N") {
    & "$Root\scripts\smoke_minimal.ps1"
    if ($LASTEXITCODE -ne 0) {
        Write-Warn "Smoke failed — check Python version and ingest"
        exit $LASTEXITCODE
    }
}

# --- Done ---
$port = if ($env:ZOOPLUS_DEV_PORT) { $env:ZOOPLUS_DEV_PORT } else { "8090" }
Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "  Setup complete" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Start server:  .\scripts\run_dev.ps1"
Write-Host "  Chat UI:       http://127.0.0.1:${port}/ui/"
Write-Host "  Swagger:       http://127.0.0.1:${port}/docs"
Write-Host "  Health:        http://127.0.0.1:${port}/health"
Write-Host ""
Write-Host "  Docs: docs/QUICKSTART.md  |  Git flow: docs/GIT_WORKFLOW.md"
Write-Host ""
